version: '3.1'

services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
      
  # Wordpress
  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    restart: always
    ports:
      - '8081:80'
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite

  # php
  phpmyadmin:
    depends_on:
      - db
    platform: linux/x86_64
    image: phpmyadmin
    restart: always
    ports:
      - '8082:80'
    environment:
      PMA_HOSTS: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data:

# to start up, use the command docker-compose up -d